/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Giulia Chindea and Ken Wu
 * ICS4UE-11
 * July 25, 2022
 * This program allows the first player to enter a real word that the second player will try to guess. 
 * The first player can also specify how many guesses to give. 
 */

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

public class Player1 extends javax.swing.JFrame {
    
    private static String[] letters;
    private static int numGuesses;
    private static String word;
    
    /**
     * Creates new form Game
     */
    public Player1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guesses_btnGroup = new javax.swing.ButtonGroup();
        p1_title = new javax.swing.JLabel();
        enterWord_lbl = new javax.swing.JLabel();
        p1Word_txt = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        numGuesses_6box = new javax.swing.JRadioButton();
        numGuesses_7box = new javax.swing.JRadioButton();
        numGuesses_8box = new javax.swing.JRadioButton();
        numGuesses_9box = new javax.swing.JRadioButton();
        numGuesses_10box = new javax.swing.JRadioButton();
        numGuesses_lbl = new javax.swing.JLabel();
        p1Start_btn = new javax.swing.JButton();
        backToMenu_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hangman");

        p1_title.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        p1_title.setText("Player 1");

        enterWord_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        enterWord_lbl.setText("Enter the Word: ");

        p1Word_txt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jSpinner1.setUI(null);

        guesses_btnGroup.add(numGuesses_6box);
        numGuesses_6box.setSelected(true);
        numGuesses_6box.setText("6 (default)");

        guesses_btnGroup.add(numGuesses_7box);
        numGuesses_7box.setText("7");

        guesses_btnGroup.add(numGuesses_8box);
        numGuesses_8box.setText("8");

        guesses_btnGroup.add(numGuesses_9box);
        numGuesses_9box.setText("9");

        guesses_btnGroup.add(numGuesses_10box);
        numGuesses_10box.setText("10");

        numGuesses_lbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numGuesses_lbl.setText("Select the Number of Guesses: ");

        p1Start_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        p1Start_btn.setText("Start");
        p1Start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1Start_btnActionPerformed(evt);
            }
        });

        backToMenu_btn.setText("Back to Menu");
        backToMenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenu_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backToMenu_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p1_title)
                .addGap(329, 329, 329))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterWord_lbl)
                                .addGap(37, 37, 37)
                                .addComponent(p1Word_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numGuesses_lbl)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numGuesses_10box)
                                    .addComponent(numGuesses_9box)
                                    .addComponent(numGuesses_8box)
                                    .addComponent(numGuesses_7box)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numGuesses_6box)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(p1Start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1_title)
                    .addComponent(backToMenu_btn))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterWord_lbl)
                    .addComponent(p1Word_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numGuesses_6box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numGuesses_7box)
                    .addComponent(numGuesses_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numGuesses_8box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numGuesses_9box)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numGuesses_10box)
                .addGap(18, 18, 18)
                .addComponent(p1Start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1Start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1Start_btnActionPerformed
        // TODO add your handling code here:
        if(p1Word_txt.getText().isEmpty()){
            // displays error telling user that they did not enter a word
            JOptionPane.showMessageDialog(rootPane, "Word input missing.", "Error", HEIGHT);
        }
        else{
            // gets the word from player1 input
            word = p1Word_txt.getText().toLowerCase();
            // checks if the word is a real word
            if(!word_check(word)){
                // displays error telling user that the word does not exist
                JOptionPane.showMessageDialog(rootPane, "Word does not exist in our database.", "Error", HEIGHT);
            }
            else{
                // creates an array of the length of the word which will store each individual letter
                letters = new String[word.length()];
                // loops through each character in the word and stores it in the array, forcing each letter to be lowercase
                for(int i = 0; i < word.length(); i++){
                    letters[i] = String.valueOf(word.charAt(i));
                }

                // checks how many guesses player1 wants to give
                if(numGuesses_7box.isSelected()){
                    numGuesses = 7;
                }
                else if(numGuesses_8box.isSelected()){
                    numGuesses = 8;
                }
                else if(numGuesses_9box.isSelected()){
                    numGuesses = 9;
                }
                else if(numGuesses_10box.isSelected()){
                    numGuesses = 10;
                }
                // defaults to 6 guesses
                else{
                    numGuesses = 6;
                }

                // opens Player2 jFrame form
                this.setVisible(false);
                new Player2().setVisible(true);
            }
        }
    }//GEN-LAST:event_p1Start_btnActionPerformed

    private void backToMenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenu_btnActionPerformed
        // TODO add your handling code here:
        // returns to Menu jFrame form
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_backToMenu_btnActionPerformed

    public static String getWord(){
        return word;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player1().setVisible(true);
            }
        });
    }
    
    public static boolean word_check(String word) {
        // System.out.println(word);
        try{
            try ( // creates a BufferedReader to quickly read through the dictionary file
                    BufferedReader in = new BufferedReader(new FileReader("dictionary.txt"))) {
                String str;
                // loops through the list of words in the dictionary file
                while ((str = in.readLine()) != null){
                    // if the file contains the word, returns true
                    if (str.contains(word)){
                        return true;
                    }
                }
            }
        } 
        catch (IOException e) {
        }
        // returns false if the file does not contain the word
        return false;
    }
    
    // returns the array of individual letters
    public static String[] getLetters(){
        return letters;
    }
    
    // returns the number of guesses that player 2 will have
    public static int getGuesses(){
        return numGuesses;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenu_btn;
    private javax.swing.JLabel enterWord_lbl;
    private javax.swing.ButtonGroup guesses_btnGroup;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JRadioButton numGuesses_10box;
    private javax.swing.JRadioButton numGuesses_6box;
    private javax.swing.JRadioButton numGuesses_7box;
    private javax.swing.JRadioButton numGuesses_8box;
    private javax.swing.JRadioButton numGuesses_9box;
    private javax.swing.JLabel numGuesses_lbl;
    private javax.swing.JButton p1Start_btn;
    private javax.swing.JTextField p1Word_txt;
    private javax.swing.JLabel p1_title;
    // End of variables declaration//GEN-END:variables
}
